### ISSUE TITLE
interactive mode error

### ISSUE THREAD

**Issue by DominikSzabo1** [timschneeb/KomootGPX#15]
Hi, 
thanks for your great tool! 

It's not a big deal, but when running it in interactive mode on MacOS, I'm encountering an error  after entering the tour id:

```
Traceback (most recent call last):
  File "/Users/XXX/miniconda3/bin/komootgpx", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/komootgpx/komootgpx.py", line 181, in entrypoint
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/miniconda3/lib/python3.11/site-packages/komootgpx/komootgpx.py", line 162, in main
    if not anonymous and tour_selection != "all" and int(tour_selection) not in tours:
                                                     ^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '--help'
```

The non-interactive mode is working fine (e.g. komootgpx -n -d 1691652230)

**Comment by marcin-gryszkalis** [comment]
@DominikSzabo1 how did you call komootgpx to get this traceback?
I can confirm that for full interactive mode (no params, entered login+pass+id) I'm getting `KeyError` in 
```  
File "/home/mg/git/KomootGPX/komootgpx/komootgpx.py", line 173, in main
    make_gpx(tour_selection, api, output_dir, no_poi, skip_existing, tours[tour_selection], add_date)
                                                                     ~~~~~^^^^^^^^^^^^^^^^
```

and for calling with `-n` only I'm getting json parser error in 
```
  File "/home/mg/git/KomootGPX/komootgpx/api.py", line 72, in print_tours
    tours = self.fetch_tours(tourType, silent=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

this needs more robust testing :) I'll check later tonight.

**Comment by marcin-gryszkalis** [comment]
btw. as stated in README: `-n, --anonymous                    Skip authentication, no interactive prompt, valid only with -d` - although test for this condition doesn't work.

**Comment by Jomme5** [comment]
Same
Windows, Python 3

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\komootgpx.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\komootgpx\komootgpx.py", line 181, in entrypoint
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\komootgpx\komootgpx.py", line 173, in main
    make_gpx(tour_selection, api, output_dir, no_poi, skip_existing, tours[tour_selection], add_date)
                                                                     ~~~~~^^^^^^^^^^^^^^^^
KeyError: '1696386925'
```

**Comment by timschneeb** [comment]
#16 should fix this issue. 

I pushed a new version (v1.3.1) of this package to the PyPi repository.

**Comment by DominikSzabo1** [comment]
Thanks for the quick fix @timschneeb! 

For noobs like me: you can update to version 1.3.1 with the command:
`pip install komootgpx -U`
